### ISSUE TITLE
selection variable has the last value if all selected option is removed

### ISSUE THREAD

**Issue by subdesign** [tristanjahier/chosen-order#15]
So when I remove all the selected options from the edit field, the **selection** variable holds the last added option. It should be an empty object, right?
Using __var selection = $('#my-list').getSelectionOrder();__ function.

Also, If I have 2 selected options, and I remove 1, dumping selected variable shows 2 items. It's no purpose to be synced with the select element?

**Comment by subdesign** [comment]
Okay, solved with the following command in the change() closure:
$(this).trigger("chosen:updated");

**Comment by tristanjahier** [comment]
Hello @subdesign! I think this is a duplicate of #2, #6 and #7.

You can find help in this section (part of another branch): https://github.com/tristanjahier/chosen-order/blob/2.x/dev/README.md#binding-selection-retrieval-on-chosen-change-event
