### ISSUE TITLE
Bad selection when removing items on multiselect

### ISSUE THREAD

**Issue by mikamboo** [tristanjahier/chosen-order#6]
ChosenOrder.getSelectionOrder not working correctly when we removing items from chosen selcetion. 
It return a liste with items which supposed to be removed from selection. 

```
$(".chosen-select").on('change', function(evt, params) {
    var selection = ChosenOrder.getSelectionOrder($(".chosen-select"));

    //-- selection contains correct list of items sorted when adding new items
    //-- selection contains incorrect list of items sorted when removing items
}
```

**Comment by tristanjahier** [comment]
Hi @mikamboo!

This problem has already been discussed here: https://github.com/tristanjahier/chosen-order/issues/2. As you're going to see, there are 2 workarounds, suggested by @jgoyvaerts and @juliankatz1991.

Also, for a description of the problem, see the README.md of the `2.0/dev` branch, which I am working on: https://github.com/tristanjahier/chosen-order/blob/2.x/dev/README.md#binding-selection-retrieval-on-chosen-change-event

Let me know if i understood well your problem and if you solve it.

**Comment by mikamboo** [comment]
HI @tristanjahier !

Yes it's exactly the same problem as #2 and now, i have a better understanding about it. 
I will use your suggested hacks.

Thanks for all.
