### ISSUE TITLE
How To Use Chosen-order in a website built with bootstrap with chosen enabled multiselection

### ISSUE THREAD

**Issue by Macwilcy** [tristanjahier/chosen-order#8]
Hi @tristanjahier ,

How is France.

How can I use your Chosen-order in a website built with bootstrap with chosen enabled multi selection so as to keep the selection order as selected by the user

I am really new in javascript.

I have tried so options but couldn't get to work. I would really appreciate your help.

I use php very more.

Please, how can I implement your script. Please tell me what to do and how to do it. Please, Thanks alot

**Comment by Macwilcy** [comment]
Hi @tristanjahier ,

In details with the above:

I have this Chosen enabled bootstrap multi-selection:

```
                    <div class="control-group">
                            <label class="control-label" for="selectError3">Select Quantity : </label>
                                <div class="controls">
                                    <select name="qty[]" required multiple id="selectError3" data-     
                                        rel="chosen" class="span7" data-validation-engine='validate[required]'>
                                                <option value='1'>1</option>
                                                <option value='2'>2</option>
                                                <option value='3'>3</option>
                                                <option value='4'>4</option>
                                                <option value='5'>5</option>
                </select>
                                </div>
                        </div>
```
1. Should I replace this  id="selectError3 my-list" with your id="my-list" ? 
   or
   should I combine your id="my-list" with the bootstrap chosen  id="selectError3" so it would look like this  id="selectError3 my-list" ?
2. Should I replace bootstrap chosen js `<script src="js/jquery.chosen.min.js"></script> with your own <script type="text/javascript" src="chosen.order.jquery.min.js"></script>`
                                  OR
   should I combine the two ?:
   `<script src="js/jquery.chosen.min.js"></script>
   <script type="text/javascript" src="chosen.order.jquery.min.js"></script>`
3. You said the two works :
                           ChosenOrder.getSelectionOrder(document.getElementById('my-list'));
                           ChosenOrder.getSelectionOrder($('#my-list'));
   which one do you think will work best in my case ?
4. I have more than 1 chosen enabled mult-selection in one page. Please how can I get them work with your script so I can get each of them in the order the user selected each.
5. Is there a special way for me to retrieve the data using PHP ?
6. It is really urgent for me to get this working
7. Please, I really need your help.
8. Thank you so much

**Comment by Macwilcy** [comment]
Hello, @tristanjahier , please, am still waiting for your reply.

I really need your assistance. Thank you

**Comment by tristanjahier** [comment]
Hi @Macwilcy, sorry for the wait.
1. It is not required to put an ID on the `<select>` element. It is only useful to ease selecting the element. Moreover, "my-list" is just an example, it could be "selectError3" or whatever you want.
   **Be careful**, you must not have multiple IDs like that: `id="selectError3 my-list"`.
2. You must have both. `jquery.chosen.min.js` for Chosen and `chosen.order.jquery.min.js` for my script.
3. Yep the 2 methods are completely equivalent. You can use whatever you want. But jQuery might be easier for a JavaScript learner. Plus, if you are already using jQuery extensively in your application, it would be more consistent and compact.
4. If you are able to get your `<select>` elements (with jQuery or JavaScript native API), you will be able to get the selections of these elements. It's that simple:
   
   ``` javascript
   // These examples use jQuery
   var selection1 = $('#element1').getSelectionOrder();
   var selection2 = $('#my-list').getSelectionOrder();
   var selection3 = $('.dropdown.large').getSelectionOrder();
   var selection4 = $('#selectError3').getSelectionOrder();
   ...
   ```
5. No special thing here. You can send the data to the server as you wish. With an Ajax request or by inputting the ordered selection in a hidden HTML field before submitting the form.
6. 7 8 You're welcome.

**Comment by Macwilcy** [comment]
@tristanjahier Thanks for your reply. I really appreciate. Let me work it

Thanks again
