### ISSUE TITLE
Suggestion for integration

### ISSUE THREAD

**Issue by antongorodezkiy** [tristanjahier/chosen-order#9]
Hello,

Just a suggestion for integration with https://github.com/M3nace/jquery-chosen-sortable

**Comment by tristanjahier** [comment]
Hello @antongorodezkiy and thank you for your suggestion.

Which type of integration would you like to have?
I think that if "jquery-chosen-sortable" just provide a way to re-order elements **without altering the Chosen UI structure**, my script would nicely come along. I'm not sure which type of special integration you are thinking of.

Anyway, I am working on a similar project on my side, but I will considerate your suggestion.

**Comment by antongorodezkiy** [comment]
@tristanjahier

Actually I have no details, sorry :) I used your plugin (thanks for the good plugin!) once and today I found and used M3nace/jquery-chosen-sortable on other project for a little different task. So I found it and wanted to let you know that it's exist, so maybe it could be helpful for you.

> Anyway, I am working on a similar project on my side

Sounds good!

**Comment by tristanjahier** [comment]
But did you try to use both at the same time? And if so, did you run into issues?

**Comment by antongorodezkiy** [comment]
I didn't try both at the same time so far
